Works wrong
polina-nn/news pull request #29
Opened 2023-02-17 10:33 UTC by polina-nn

2023-02-20 15:17 UTC, pavelzarubin requested changes

2023-02-20 15:17 UTC, pavelzarubin commented on src/EndPoints/AddOneImage.hs
> +      lift $ Logger.logDebug (News.hLogHandle h) "checkImageFileExist: OK!"
тут конечно лучше liftIO

2023-02-20 15:17 UTC, pavelzarubin commented on src/EndPoints/AddOneImage.hs
> +      EX.except (Right r)
`return r` ????

2023-02-20 15:17 UTC, pavelzarubin commented on src/EndPoints/AddOneImage.hs
> +      lift $ Logger.logDebug (News.hLogHandle h) "checkPngImage: OK!"
далее аналогично

2023-02-20 15:17 UTC, pavelzarubin commented on src/EndPoints/AddOneImage.hs
> +  let checkUserAuthor = EX.withExceptT ErrorTypes.InvalidPermissionAddImage (Lib.checkUserAuthor' h user)
а почему просто не связать все через `>>`? просто все четыре проверки связать, сигнатура и поведение будут те же

2023-02-26 17:38 UTC, polina-nn commented
Доброе утро! Павел! Добавила ExceptT во все эндпойты... Дальше будем запихивать  ExceptT поглубже в сервант, и переделывать хенд, чтобы легко перейти на другую базу ? но это уже в другом ишью...

2023-02-27 07:56 UTC, pavelzarubin requested changes

2023-02-27 07:56 UTC, pavelzarubin commented on src/EndPoints/AddOneCategory.hs
> +    categories <- CategoryIO.getAllCategories conn
А зачем тебе получать все категории, и только после проверять, что пользователь админ?
Проще сделать не функцию `allCheck`, а вызывать функции проверки в ходе  работы `addCategoryExcept`.

2023-02-27 07:56 UTC, pavelzarubin commented on src/EndPoints/AddOneCategory.hs
> +addCategoryToDb ::
Вот как раз такие функции и нужно прятать в handler, так как здесь есть работа с IO.

2023-02-27 14:43 UTC, pavelzarubin approved these changes

2023-02-27 14:43 UTC, pavelzarubin commented on src/EndPoints/AddOneImage.hs
> +  allCheckAndDecodeBase64ByteString <- checkImageFileExist h createImage >> checkPngImage h createImage >> checkAndDecodeBase64Image h createImage
```haskell
allCheckAndDecodeBase64ByteString <- checkImageFileExist h createImage 
checkPngImage h createImage
checkAndDecodeBase64Image h createImage
```

2023-02-28 15:57 UTC, merged