#3_Connect_to_DB
polina-nn/news pull request #31
Opened 2023-03-01 15:53 UTC by polina-nn

2023-03-09 11:14 UTC, polina-nn commented
Переделала на Generalized Authentication in Action по инструкции в руководстве к серванту. 
Вроде работает...

2023-03-14 07:33 UTC, pavelzarubin requested changes

2023-03-14 07:33 UTC, pavelzarubin commented on src/EndPoints/AddOneCategory.hs
> +addCategoryExcept _ (h, account, r) =
Так выходит не получаешь соединения из пула, а каждый раз создаешь новое. Зачем? Ты же можешь перехватить ошибку о потере соединения с базой, когда делаешь в базу запрос. К тому же здесь ты соединения не закрываешь.

2023-03-14 07:33 UTC, pavelzarubin commented on src/EndPoints/AddOneCategory.hs
> +addCategoryExcept _ (h, account, r) =
https://hackage.haskell.org/package/postgresql-simple-0.6.5/docs/Database-PostgreSQL-Simple.html#:~:text=that%20return%20results-,query,-%3A%3A%20(ToRow%20q

почитай про ошибки которые бросает postgresql-simple

2023-03-14 07:33 UTC, pavelzarubin commented on src/EndPoints/Lib/LibIO.hs
> +countAccounts :: News.Handle IO -> SQL.Connection -> ByteString -> EX.ExceptT ErrorTypes.ServerAuthError IO Int
Это зачем? Ты в предыдущей функции сопоставление делаешь, где один аккаунт. Зачем лишний запрос?

2023-03-14 07:33 UTC, pavelzarubin commented on src/Types/DataTypes.hs
> +newtype Account = Account {unAccount :: T.Text}
может это Token, а не Account?

2023-03-14 07:39 UTC, pavelzarubin commented on _migrations/02.sql
> +CREATE TABLE IF NOT EXISTS cookie (
я бы это назвал не cookie, а tokens. К тому же primary_key лучше не логин, а id пользователя и связать это с таблицей пользователей. 
Следующие исправления можно не вносить, так как и так работы много.
Я бы на твоем месте для токенов добавил эндпоинт для аутентификации. А сами токены сделал бы временными. То есть в данной таблице хранил бы время создания. А для сервера бы добавил параметр в конфиг (или захардкодил) время жизни токена. Эндпоинт аутентификации бы просто этот токено мог бы обновлять.

2023-03-27 17:51 UTC, polina-nn commented on _migrations/02.sql
> +CREATE TABLE IF NOT EXISTS cookie (
Добрый день! 
Поправила. 
1. EXS.try (SQL.query...) добавила только в первую функцию, которая вызывается при запросе
2. У меня нет в таблице пользователей id (так как нет запросов на редактирование и удаление пользователей), а есть только логин
3. Так и не удалось мне сделать, чтобы при восстановлении соединения с базой восстанавливалась работа сервера. Как я могу понять в коде, что соединение восстановилось?

2023-03-30 15:42 UTC, polina-nn commented on _migrations/02.sql
> +CREATE TABLE IF NOT EXISTS cookie (
Добавила EXS.try (SQL.query... ) во все запросы, по ходу дела, некоторые запросы переписала

2023-03-31 06:44 UTC, pavelzarubin approved these changes

2023-03-31 08:08 UTC, merged