4_category
polina-nn/news pull request #35
Opened 2023-04-10 13:26 UTC by polina-nn

2023-04-11 06:28 UTC, pavelzarubin requested changes

2023-04-11 06:28 UTC, pavelzarubin commented on _migrations/01.sql
> +   category_parent_id INT NOT NULL);
почему NOT NULL? У нас что категорий без родителя не бывает?

2023-04-11 06:28 UTC, pavelzarubin commented on src/EndPoints/EditOneCategory.hs
> +checkCategoryName ::
а зачем нужны эти проверки? У тебя же база данных это может проверить самостоятельно и тогда тебе вернется ошибка, которую можно обработать.

2023-04-11 06:28 UTC, pavelzarubin commented on src/EndPoints/AddOneNews.hs
> +checkCategoryId pool h r@DataTypes.CreateNewsRequest {..} = do
вынеси это отдельно, у тебя в другом модуле код повторяется

2023-04-12 13:59 UTC, polina-nn commented
Здравствуй!
1. Поправила миграции
 Взяла миграции из master (01.sql и 02.sql) и добавила 03.sql . При этом все старые категории (у которых были paths) преобразовались в корневые категории. Так пойдет?  
2. Вынесла в отдельную функцию checkCategoryExsistById
3. Удалила работу с sequence, теперь сразу возвращаю id при создании новости или картинки.
4. Токен теперь создается после создания пользователя.
5. Убрала проверку уникальности для логина и имени категории из отдельных функций. Теперь отлавливается ошибка непосредственно внутри запроса на создание пользователя / создание (редактирование) категории
Вроде всё из того, что мы с тобой обсуждали во вторник.

2023-04-13 05:03 UTC, pavelzarubin approved these changes

2023-04-13 10:02 UTC, merged