19 use newtype
polina-nn/news pull request #36
Opened 2023-04-14 13:38 UTC by polina-nn

2023-04-15 09:27 UTC, polina-nn commented
Доброе утро! Проверила работу тестов и сбилдила, можно смотреть ....

2023-04-15 14:37 UTC, roman-bodavskiy commented on _migrations/04.sql
> +ALTER TABLE news  ADD COLUMN news_id BIGINT GENERATED ALWAYS AS IDENTITY  (START WITH 1 INCREMENT BY 1);
А зачем вообще нужна эта миграция? Сначала у тебя было 
`news_id     BIGINT NOT NULL PRIMARY KEY, `

Потом в третьей миграции:
```
ALTER TABLE image  ALTER COLUMN image_id ADD GENERATED ALWAYS AS IDENTITY;
DROP SEQUENCE IF EXISTS  image_id_seq;
```
зачем это нужно менять?

2023-04-15 15:08 UTC, polina-nn commented on _migrations/04.sql
> +ALTER TABLE news  ADD COLUMN news_id BIGINT GENERATED ALWAYS AS IDENTITY  (START WITH 1 INCREMENT BY 1);
Добрый вечер! 
Изначально в 1 миграции у меня была создана последовать (SEQUENCE ), я сначала получала id_news для новой новости и затем в эту id_news записывала  новость. (То есть было два запроса). И соответвенно у поля news_id не было генерации. 
Теперь я возвращаю автоматичеки сгенерированный id_news сразу из функции добавления новости в базу...
Такая была задумка после третьей миграции.
Но после тестирования на миграции заполненной бызы выяснилось, что после третьей миграции отсчет начинается снова с id_news = 1, и невозможно добавить в старую базу новую новость.
Таким образом и получилась четвертая миграция, где я как-бы перенумерую уже созданные новости, и id_news для новых новостей получается уже валидным.
Пока так....

2023-04-15 15:11 UTC, polina-nn commented on _migrations/04.sql
> +ALTER TABLE news  ADD COLUMN news_id BIGINT GENERATED ALWAYS AS IDENTITY  (START WITH 1 INCREMENT BY 1);
https://github.com/polina-nn/news/issues/19 
В комментариях к ишью я это написала...

2023-04-17 10:12 UTC, roman-bodavskiy commented on src/EndPoints/Lib/Category/CategoryIO.hs
> +  Int ->
А почему здесь опять `Int` вместо `Id`?
Паша предлрожил тебе  сделать id привязанный к сущности, используя фантомные типы:
`newtype Id a = Id {getId :: Int}`
Тип `a` здесь называется фантомным, так как он не появляется в правой части выражения, только в левой используется для типобезопасности.
Таким образом здесь у тебя будет тип `Id Category` и ты никогда не перепутаешь его например с `Id News` или `Id User.` Подобный тип `Id` мы используем на проекте

2023-04-17 10:58 UTC, pavelzarubin commented on src/EndPoints/Lib/Category/Category.hs
> +toCategory :: (Int, DataTypes.Name, Int) -> DataTypes.Category
а зачем тебе эта функция? Ты же можешь сразу из запроса получать Id вне как Int, а как Id Category?

2023-04-17 11:04 UTC, pavelzarubin commented on src/Types/DataTypes.hs
> +newtype Id = Id {id :: Int}
как уже было сказано тип должен быть параметризован. Иначе у тебя будет много одинаковых `Id`. Например в том же `ParentId`, если хочешь его выделить отдельно (хотя как по мне это лишнее), должен быть ` ParentId { parentId :: Id Category}`

2023-04-18 18:00 UTC, polina-nn commented on src/EndPoints/Lib/Category/CategoryIO.hs
> +  Int ->
Хорошо, поправлю... В newtype Id a = Id {getId :: Int} параметр a, я только сейчас заметила, когда слово фантомный прочитала.

2023-04-20 06:50 UTC, pavelzarubin requested changes

2023-04-20 06:50 UTC, pavelzarubin commented on src/Types/DataTypes.hs
> +data ImageId
Зачем? Ты же можешь просто использовать уже имеющиеся типы Category, News, Image

2023-04-20 06:50 UTC, pavelzarubin commented on src/EndPoints/GetOneImage.hs
> +                (SQL.Only $ DataTypes.getId id')
зачем тебе вызывать `getId`, если для `Id` у тебя есть инстанс `ToRow`?

2023-04-20 08:24 UTC, pavelzarubin commented on src/EndPoints/Lib/News/NewsIO.hs
> +      return $ DataTypes.Id {getId = idIm}
Надо наверное было сразу написать. У тебя еще есть `FromRow`. Из базы можно сразу `Id` вытаскивать.

2023-04-20 09:40 UTC, pavelzarubin approved these changes

2023-04-20 12:19 UTC, merged